### ISSUE TITLE
Can't send a HTTP request to our Docker container

### ISSUE THREAD

**Issue by ChristofferHolmesland** [DAT210/web#4]
Following the guide in the README file we've done the following
-  We're running our docker container ```docker run --network=frontend -p 81:80 -d payment_api```. This should connect our container to the same network as web.
- web server started using ```docker-compose up --build```

When we're sending a request to our container ```response = requests.get("http://payment_api:81/payment-pages/5?page=payment")```, we get this error ```socket.gaierror: [Errno -2] Name or service not known```

 [routes.py](https://github.com/DAT210/web/blob/group7-payment/restaurant/blueprints/group7/payment/routes.py)

**Comment by NeonNoize** [comment]
I think i found your errors:
 docker run --network=frontend --name payment_api --hostname payment_api -p 81:80 -t -d payment_api python3 app.py 

response = requests.get("http://payment_api:80/payment-pages/5?page=payment")

changes:
docker run:
 now has a name that can be called from other docker networks
"python3 app.py" is to run a file on your api called app.py. you can change this based on what you are using. I can't guarantee that this line is absolutely necessary.
response:
changed to port 80. you need to send api request to the open port "80" to get any response. 
youAPI port 81<==>port:80<==>port:80 Server
 other:
you may need to expose port 80 in your dockerfile
